language: php
php:
  - 7.4.29
os: linux

before_script:
  - phpenv config-add myconfig.ini
  - rm -rf composer.lock
  - composer install
  - cp .env.example .env
  - php artisan key:generate
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml
after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v